//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN2LNJ.FilmRatingsServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cara.org/", ConfigurationName="FilmRatingsServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithNoRating", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse GetTitleListStringWithNoRating(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithNoRating", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse> GetTitleListStringWithNoRatingAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest request);
        
        // CODEGEN: Generating message contract since element name year from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithRatingYear", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse GetTitleListStringWithRatingYear(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithRatingYear", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse> GetTitleListStringWithRatingYearAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithPagination", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse GetTitleListStringWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringWithPagination", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse> GetTitleListStringWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringFullWithPagination", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse GetTitleListStringFullWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringFullWithPagination", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse> GetTitleListStringFullWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringFullForExport", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse GetTitleListStringFullForExport(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListStringFullForExport", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse> GetTitleListStringFullForExportAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest request);
        
        // CODEGEN: Generating message contract since element name year from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingWithPagination", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse GetTitleListByYearRatingWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingWithPagination", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse> GetTitleListByYearRatingWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest request);
        
        // CODEGEN: Generating message contract since element name year from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingFullWithPagination", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse GetTitleListByYearRatingFullWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingFullWithPagination", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse> GetTitleListByYearRatingFullWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest request);
        
        // CODEGEN: Generating message contract since element name year from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingForExport", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse GetTitleListByYearRatingForExport(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetTitleListByYearRatingForExport", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse> GetTitleListByYearRatingForExportAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetExportWithTitleYear", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse GetExportWithTitleYear(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetExportWithTitleYear", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse> GetExportWithTitleYearAsync(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://cara.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetExportWithTitle", ReplyAction="*")]
        SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse GetExportWithTitle(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cara.org/GetExportWithTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse> GetExportWithTitleAsync(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithNoRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithNoRating", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequestBody Body;
        
        public GetTitleListStringWithNoRatingRequest() {
        }
        
        public GetTitleListStringWithNoRatingRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithNoRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public GetTitleListStringWithNoRatingRequestBody() {
        }
        
        public GetTitleListStringWithNoRatingRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithNoRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithNoRatingResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponseBody Body;
        
        public GetTitleListStringWithNoRatingResponse() {
        }
        
        public GetTitleListStringWithNoRatingResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithNoRatingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListStringWithNoRatingResult;
        
        public GetTitleListStringWithNoRatingResponseBody() {
        }
        
        public GetTitleListStringWithNoRatingResponseBody(string GetTitleListStringWithNoRatingResult) {
            this.GetTitleListStringWithNoRatingResult = GetTitleListStringWithNoRatingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithRatingYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithRatingYear", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequestBody Body;
        
        public GetTitleListStringWithRatingYearRequest() {
        }
        
        public GetTitleListStringWithRatingYearRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithRatingYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rating;
        
        public GetTitleListStringWithRatingYearRequestBody() {
        }
        
        public GetTitleListStringWithRatingYearRequestBody(string year, string rating) {
            this.year = year;
            this.rating = rating;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithRatingYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithRatingYearResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponseBody Body;
        
        public GetTitleListStringWithRatingYearResponse() {
        }
        
        public GetTitleListStringWithRatingYearResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithRatingYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListStringWithRatingYearResult;
        
        public GetTitleListStringWithRatingYearResponseBody() {
        }
        
        public GetTitleListStringWithRatingYearResponseBody(string GetTitleListStringWithRatingYearResult) {
            this.GetTitleListStringWithRatingYearResult = GetTitleListStringWithRatingYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithPaginationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithPagination", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequestBody Body;
        
        public GetTitleListStringWithPaginationRequest() {
        }
        
        public GetTitleListStringWithPaginationRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithPaginationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int endRow;
        
        public GetTitleListStringWithPaginationRequestBody() {
        }
        
        public GetTitleListStringWithPaginationRequestBody(string search, int startRow, int endRow) {
            this.search = search;
            this.startRow = startRow;
            this.endRow = endRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringWithPaginationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringWithPaginationResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponseBody Body;
        
        public GetTitleListStringWithPaginationResponse() {
        }
        
        public GetTitleListStringWithPaginationResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringWithPaginationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListStringWithPaginationResult;
        
        public GetTitleListStringWithPaginationResponseBody() {
        }
        
        public GetTitleListStringWithPaginationResponseBody(string GetTitleListStringWithPaginationResult) {
            this.GetTitleListStringWithPaginationResult = GetTitleListStringWithPaginationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringFullWithPaginationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringFullWithPagination", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequestBody Body;
        
        public GetTitleListStringFullWithPaginationRequest() {
        }
        
        public GetTitleListStringFullWithPaginationRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringFullWithPaginationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int endRow;
        
        public GetTitleListStringFullWithPaginationRequestBody() {
        }
        
        public GetTitleListStringFullWithPaginationRequestBody(string search, int startRow, int endRow) {
            this.search = search;
            this.startRow = startRow;
            this.endRow = endRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringFullWithPaginationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringFullWithPaginationResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponseBody Body;
        
        public GetTitleListStringFullWithPaginationResponse() {
        }
        
        public GetTitleListStringFullWithPaginationResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringFullWithPaginationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListStringFullWithPaginationResult;
        
        public GetTitleListStringFullWithPaginationResponseBody() {
        }
        
        public GetTitleListStringFullWithPaginationResponseBody(string GetTitleListStringFullWithPaginationResult) {
            this.GetTitleListStringFullWithPaginationResult = GetTitleListStringFullWithPaginationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringFullForExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringFullForExport", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequestBody Body;
        
        public GetTitleListStringFullForExportRequest() {
        }
        
        public GetTitleListStringFullForExportRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringFullForExportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public GetTitleListStringFullForExportRequestBody() {
        }
        
        public GetTitleListStringFullForExportRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListStringFullForExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListStringFullForExportResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponseBody Body;
        
        public GetTitleListStringFullForExportResponse() {
        }
        
        public GetTitleListStringFullForExportResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListStringFullForExportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListStringFullForExportResult;
        
        public GetTitleListStringFullForExportResponseBody() {
        }
        
        public GetTitleListStringFullForExportResponseBody(string GetTitleListStringFullForExportResult) {
            this.GetTitleListStringFullForExportResult = GetTitleListStringFullForExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingWithPaginationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingWithPagination", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequestBody Body;
        
        public GetTitleListByYearRatingWithPaginationRequest() {
        }
        
        public GetTitleListByYearRatingWithPaginationRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingWithPaginationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rating;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int endRow;
        
        public GetTitleListByYearRatingWithPaginationRequestBody() {
        }
        
        public GetTitleListByYearRatingWithPaginationRequestBody(string year, string rating, int startRow, int endRow) {
            this.year = year;
            this.rating = rating;
            this.startRow = startRow;
            this.endRow = endRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingWithPaginationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingWithPaginationResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponseBody Body;
        
        public GetTitleListByYearRatingWithPaginationResponse() {
        }
        
        public GetTitleListByYearRatingWithPaginationResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingWithPaginationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListByYearRatingWithPaginationResult;
        
        public GetTitleListByYearRatingWithPaginationResponseBody() {
        }
        
        public GetTitleListByYearRatingWithPaginationResponseBody(string GetTitleListByYearRatingWithPaginationResult) {
            this.GetTitleListByYearRatingWithPaginationResult = GetTitleListByYearRatingWithPaginationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingFullWithPaginationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingFullWithPagination", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequestBody Body;
        
        public GetTitleListByYearRatingFullWithPaginationRequest() {
        }
        
        public GetTitleListByYearRatingFullWithPaginationRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingFullWithPaginationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rating;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int endRow;
        
        public GetTitleListByYearRatingFullWithPaginationRequestBody() {
        }
        
        public GetTitleListByYearRatingFullWithPaginationRequestBody(string year, string rating, int startRow, int endRow) {
            this.year = year;
            this.rating = rating;
            this.startRow = startRow;
            this.endRow = endRow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingFullWithPaginationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingFullWithPaginationResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponseBody Body;
        
        public GetTitleListByYearRatingFullWithPaginationResponse() {
        }
        
        public GetTitleListByYearRatingFullWithPaginationResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingFullWithPaginationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListByYearRatingFullWithPaginationResult;
        
        public GetTitleListByYearRatingFullWithPaginationResponseBody() {
        }
        
        public GetTitleListByYearRatingFullWithPaginationResponseBody(string GetTitleListByYearRatingFullWithPaginationResult) {
            this.GetTitleListByYearRatingFullWithPaginationResult = GetTitleListByYearRatingFullWithPaginationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingForExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingForExport", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequestBody Body;
        
        public GetTitleListByYearRatingForExportRequest() {
        }
        
        public GetTitleListByYearRatingForExportRequest(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingForExportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rating;
        
        public GetTitleListByYearRatingForExportRequestBody() {
        }
        
        public GetTitleListByYearRatingForExportRequestBody(string year, string rating) {
            this.year = year;
            this.rating = rating;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleListByYearRatingForExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleListByYearRatingForExportResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponseBody Body;
        
        public GetTitleListByYearRatingForExportResponse() {
        }
        
        public GetTitleListByYearRatingForExportResponse(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetTitleListByYearRatingForExportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTitleListByYearRatingForExportResult;
        
        public GetTitleListByYearRatingForExportResponseBody() {
        }
        
        public GetTitleListByYearRatingForExportResponseBody(string GetTitleListByYearRatingForExportResult) {
            this.GetTitleListByYearRatingForExportResult = GetTitleListByYearRatingForExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportWithTitleYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportWithTitleYear", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequestBody Body;
        
        public GetExportWithTitleYearRequest() {
        }
        
        public GetExportWithTitleYearRequest(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetExportWithTitleYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string year;
        
        public GetExportWithTitleYearRequestBody() {
        }
        
        public GetExportWithTitleYearRequestBody(string search, string year) {
            this.search = search;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportWithTitleYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportWithTitleYearResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponseBody Body;
        
        public GetExportWithTitleYearResponse() {
        }
        
        public GetExportWithTitleYearResponse(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetExportWithTitleYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExportWithTitleYearResult;
        
        public GetExportWithTitleYearResponseBody() {
        }
        
        public GetExportWithTitleYearResponseBody(string GetExportWithTitleYearResult) {
            this.GetExportWithTitleYearResult = GetExportWithTitleYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportWithTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportWithTitle", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequestBody Body;
        
        public GetExportWithTitleRequest() {
        }
        
        public GetExportWithTitleRequest(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetExportWithTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public GetExportWithTitleRequestBody() {
        }
        
        public GetExportWithTitleRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportWithTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportWithTitleResponse", Namespace="http://cara.org/", Order=0)]
        public SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponseBody Body;
        
        public GetExportWithTitleResponse() {
        }
        
        public GetExportWithTitleResponse(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cara.org/")]
    public partial class GetExportWithTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExportWithTitleResult;
        
        public GetExportWithTitleResponseBody() {
        }
        
        public GetExportWithTitleResponseBody(string GetExportWithTitleResult) {
            this.GetExportWithTitleResult = GetExportWithTitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SN2LNJ.FilmRatingsServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SN2LNJ.FilmRatingsServiceReference1.ServiceSoap>, SN2LNJ.FilmRatingsServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithNoRating(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest request) {
            return base.Channel.GetTitleListStringWithNoRating(request);
        }
        
        public string GetTitleListStringWithNoRating(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequestBody();
            inValue.Body.search = search;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithNoRating(inValue);
            return retVal.Body.GetTitleListStringWithNoRatingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithNoRatingAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest request) {
            return base.Channel.GetTitleListStringWithNoRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingResponse> GetTitleListStringWithNoRatingAsync(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithNoRatingRequestBody();
            inValue.Body.search = search;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithNoRatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithRatingYear(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest request) {
            return base.Channel.GetTitleListStringWithRatingYear(request);
        }
        
        public string GetTitleListStringWithRatingYear(string year, string rating) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithRatingYear(inValue);
            return retVal.Body.GetTitleListStringWithRatingYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithRatingYearAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest request) {
            return base.Channel.GetTitleListStringWithRatingYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearResponse> GetTitleListStringWithRatingYearAsync(string year, string rating) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithRatingYearRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithRatingYearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest request) {
            return base.Channel.GetTitleListStringWithPagination(request);
        }
        
        public string GetTitleListStringWithPagination(string search, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequestBody();
            inValue.Body.search = search;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithPagination(inValue);
            return retVal.Body.GetTitleListStringWithPaginationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest request) {
            return base.Channel.GetTitleListStringWithPaginationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationResponse> GetTitleListStringWithPaginationAsync(string search, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringWithPaginationRequestBody();
            inValue.Body.search = search;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringWithPaginationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringFullWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest request) {
            return base.Channel.GetTitleListStringFullWithPagination(request);
        }
        
        public string GetTitleListStringFullWithPagination(string search, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequestBody();
            inValue.Body.search = search;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringFullWithPagination(inValue);
            return retVal.Body.GetTitleListStringFullWithPaginationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringFullWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest request) {
            return base.Channel.GetTitleListStringFullWithPaginationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationResponse> GetTitleListStringFullWithPaginationAsync(string search, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullWithPaginationRequestBody();
            inValue.Body.search = search;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringFullWithPaginationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringFullForExport(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest request) {
            return base.Channel.GetTitleListStringFullForExport(request);
        }
        
        public string GetTitleListStringFullForExport(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequestBody();
            inValue.Body.search = search;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringFullForExport(inValue);
            return retVal.Body.GetTitleListStringFullForExportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListStringFullForExportAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest request) {
            return base.Channel.GetTitleListStringFullForExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportResponse> GetTitleListStringFullForExportAsync(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListStringFullForExportRequestBody();
            inValue.Body.search = search;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListStringFullForExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest request) {
            return base.Channel.GetTitleListByYearRatingWithPagination(request);
        }
        
        public string GetTitleListByYearRatingWithPagination(string year, string rating, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingWithPagination(inValue);
            return retVal.Body.GetTitleListByYearRatingWithPaginationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest request) {
            return base.Channel.GetTitleListByYearRatingWithPaginationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationResponse> GetTitleListByYearRatingWithPaginationAsync(string year, string rating, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingWithPaginationRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingWithPaginationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingFullWithPagination(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest request) {
            return base.Channel.GetTitleListByYearRatingFullWithPagination(request);
        }
        
        public string GetTitleListByYearRatingFullWithPagination(string year, string rating, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingFullWithPagination(inValue);
            return retVal.Body.GetTitleListByYearRatingFullWithPaginationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingFullWithPaginationAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest request) {
            return base.Channel.GetTitleListByYearRatingFullWithPaginationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationResponse> GetTitleListByYearRatingFullWithPaginationAsync(string year, string rating, int startRow, int endRow) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingFullWithPaginationRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            inValue.Body.startRow = startRow;
            inValue.Body.endRow = endRow;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingFullWithPaginationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingForExport(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest request) {
            return base.Channel.GetTitleListByYearRatingForExport(request);
        }
        
        public string GetTitleListByYearRatingForExport(string year, string rating) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingForExport(inValue);
            return retVal.Body.GetTitleListByYearRatingForExportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetTitleListByYearRatingForExportAsync(SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest request) {
            return base.Channel.GetTitleListByYearRatingForExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportResponse> GetTitleListByYearRatingForExportAsync(string year, string rating) {
            SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetTitleListByYearRatingForExportRequestBody();
            inValue.Body.year = year;
            inValue.Body.rating = rating;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetTitleListByYearRatingForExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetExportWithTitleYear(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest request) {
            return base.Channel.GetExportWithTitleYear(request);
        }
        
        public string GetExportWithTitleYear(string search, string year) {
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequestBody();
            inValue.Body.search = search;
            inValue.Body.year = year;
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetExportWithTitleYear(inValue);
            return retVal.Body.GetExportWithTitleYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetExportWithTitleYearAsync(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest request) {
            return base.Channel.GetExportWithTitleYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearResponse> GetExportWithTitleYearAsync(string search, string year) {
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleYearRequestBody();
            inValue.Body.search = search;
            inValue.Body.year = year;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetExportWithTitleYearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetExportWithTitle(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest request) {
            return base.Channel.GetExportWithTitle(request);
        }
        
        public string GetExportWithTitle(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequestBody();
            inValue.Body.search = search;
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse retVal = ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetExportWithTitle(inValue);
            return retVal.Body.GetExportWithTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse> SN2LNJ.FilmRatingsServiceReference1.ServiceSoap.GetExportWithTitleAsync(SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest request) {
            return base.Channel.GetExportWithTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleResponse> GetExportWithTitleAsync(string search) {
            SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest inValue = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequest();
            inValue.Body = new SN2LNJ.FilmRatingsServiceReference1.GetExportWithTitleRequestBody();
            inValue.Body.search = search;
            return ((SN2LNJ.FilmRatingsServiceReference1.ServiceSoap)(this)).GetExportWithTitleAsync(inValue);
        }
    }
}
